"""各平台的 ApiSource 定义（数据驱动）

所有数据来源：musicdl master + 实测

新增 API 只需在此目录下加一个文件 + 几个 ApiSource 实例。
"""
from .netease import (
    NETEASE_SEARCH_SOURCES,
    NETEASE_PARSE_URL_SOURCES,
    NETEASE_PARSE_INFO_SOURCES,
    NETEASE_PARSE_LYRIC_SOURCES,
    NETEASE_PARSE_PLAYLIST_SOURCES,
)
from .qq import (
    QQ_SEARCH_SOURCES,
    QQ_PARSE_URL_SOURCES,
    QQ_PARSE_INFO_SOURCES,
    QQ_PARSE_LYRIC_SOURCES,
    QQ_PARSE_PLAYLIST_SOURCES,
)
from .kugou import (
    KUGOU_SEARCH_SOURCES,
    KUGOU_PARSE_URL_SOURCES,
    KUGOU_PARSE_INFO_SOURCES,
    KUGOU_PARSE_LYRIC_SOURCES,
    KUGOU_PARSE_PLAYLIST_SOURCES,
)
from .kuwo import (
    KUWO_SEARCH_SOURCES,
    KUWO_PARSE_URL_SOURCES,
    KUWO_PARSE_INFO_SOURCES,
    KUWO_PARSE_LYRIC_SOURCES,
    KUWO_PARSE_PLAYLIST_SOURCES,
)

__all__ = [
    'NETEASE_SEARCH_SOURCES',
    'NETEASE_PARSE_URL_SOURCES',
    'NETEASE_PARSE_INFO_SOURCES',
    'NETEASE_PARSE_LYRIC_SOURCES',
    'NETEASE_PARSE_PLAYLIST_SOURCES',
    'QQ_SEARCH_SOURCES',
    'QQ_PARSE_URL_SOURCES',
    'QQ_PARSE_INFO_SOURCES',
    'QQ_PARSE_LYRIC_SOURCES',
    'QQ_PARSE_PLAYLIST_SOURCES',
    'KUGOU_SEARCH_SOURCES',
    'KUGOU_PARSE_URL_SOURCES',
    'KUGOU_PARSE_INFO_SOURCES',
    'KUGOU_PARSE_LYRIC_SOURCES',
    'KUGOU_PARSE_PLAYLIST_SOURCES',
    'KUWO_SEARCH_SOURCES',
    'KUWO_PARSE_URL_SOURCES',
    'KUWO_PARSE_INFO_SOURCES',
    'KUWO_PARSE_LYRIC_SOURCES',
    'KUWO_PARSE_PLAYLIST_SOURCES',
]
